export const COLOR = {
    WHITE: "#FFFFFF",

    LIGHT_RED: "#F8DAD5",
    DARK_RED: "#EA9586",

    LIGHT_PINK: "#F4D0DF",
    DARK_PINK: "#DE7FA6",

    LIGHT_PURPLE: "#E1DAEE",
    DARK_PURPLE: "#AC98CD",

    LIGHT_BLUE: "#D1E1F2",
    DARK_BLUE: "#81ABD7",

    LIGHT_YELLOW: "#FDF5D4",
    DARK_YELLOW: "#F9DF80",
}